version: "3.7"
services:
  mydumper:
    image: my6889/mydumper:v1.3
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - mydumper.env
    volumes:
      - /data/mydumper/:/mysqldump